name: by hand
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      run: |
         cp ci/sdkconfig.githubaction esp32-src/clock/sdkconfig
         ci/build.sh
